[project]
name = "orchestrator"
version = "0.1.0"
description = "Blog workflow orchestrator with agentic capabilities"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "anthropic>=0.57.1",
    "httpx>=0.28.1",
    "mcp[cli]>=1.10.1",
    "python-dotenv>=1.1.1",
]
